##
# For SEO, always have: title, description, tags
# For Public visibility: isDraft

backend:
  name: git-gateway
  branch: main
media_folder: public/assets/images/uploads
public_folder: /assets/images/uploads
project_tech:
  - null
collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Tags
        name: tags
        widget: list
        field:
          label: Tag
          name: tag
          widget: string
      - label: Is Draft
        name: isDraft
        widget: boolean
        default: true
      - label: Hero Image
        name: coverImg
        widget: image
      - label: Publish Date
        name: publishedOn
        widget: datetime
        time_format: false
        date_format: DD-MMM-YYYY
      - label: Last Modified Date
        name: lastUpdatedOn
        widget: datetime
        time_format: false
        date_format: DD-MMM-YYYY
      - label: Topics
        name: topics
        widget: list
        field:
          widget: relation
          collection: topic
          search_fields:
            - topic.title
            - topic.description
          value_field: { { slug } }
          display_fields: topic.title
      - label: Body
        name: body
        widget: markdown
  - name: project
    label: Project
    folder: src/content/project
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Tags
        name: tags
        widget: list
        field:
          label: Tag
          name: tag
          widget: string
      - label: Is Draft
        name: isDraft
        widget: boolean
        default: true
      - label: Hero Image
        name: coverImg
        widget: image
      - label: Start Date
        name: startDate
        widget: datetime
        time_format: false
        date_format: DD-MMM-YYYY
        default: ""
      - label: End Date
        name: endDate
        widget: datetime
        time_format: false
        date_format: DD-MMM-YYYY
        default: ""
      - label: Body
        name: body
        widget: markdown
  - name: topic
    label: Topics
    folder: src/content/topic
    create: true
    slug: { { slug } }
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Tags
        name: tags
        widget: list
        field:
          label: Tag
          name: tag
          widget: string
      - label: Is Draft
        name: isDraft
        widget: boolean
        default: true
      - label: Hero Image
        name: coverImg
        widget: image
      - label: Icon Name
        name: iconName
        widget: string
      - label: Body
        name: body
        widget: markdown
