##
# For SEO, always have: title, description, tags
# For Public visibility: isDraft

backend:
  name: git-gateway
  branch: main
media_folder: src/assets/images/uploads
public_folder: uploads
site_url: https://sujeet.pro
display_url: https://sujeet.pro
search: false
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"
collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Description
        name: description
        widget: string
        required: true
      - label: Is Draft
        name: isDraft
        widget: boolean
        required: false
      - label: Thumbnail Image
        name: thumbnail
        widget: image
        required: false
      - label: Cover Image
        name: cover
        widget: image
        required: false
      - label: Cover Alt
        name: coverAlt
        widget: string
        required: false
      - label: Publish Date
        name: publishedOn
        widget: datetime
        time_format: false
        date_format: DD-MMM-YYYY
        required: true
      - label: Last Modified Date
        name: lastUpdatedOn
        widget: datetime
        time_format: false
        date_format: DD-MMM-YYYY
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Topics
        name: topics
        widget: list
        required: false
        field:
          label: "Topic"
          name: "topic"
          widget: relation
          collection: topic
          search_fields:
            - topic.title
            - topic.description
          value_field: "{{ slug }}"
          display_fields: ["topic.title"]
      - label: Body
        name: body
        widget: markdown
  - name: project
    label: Project
    folder: src/content/project
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Description
        name: description
        widget: string
        required: true
      - label: Is Draft
        name: isDraft
        widget: boolean
        required: false
      - label: Thumbnail Image
        name: thumbnail
        widget: image
        required: false
      - label: Start Date
        name: startDate
        widget: datetime
        time_format: false
        date_format: DD-MMM-YYYY
        required: true
      - label: End Date
        name: endDate
        widget: datetime
        time_format: false
        date_format: DD-MMM-YYYY
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Topics
        name: topics
        widget: list
        required: false
        field:
          label: "Topic"
          name: "topic"
          widget: relation
          collection: topic
          search_fields:
            - topic.title
            - topic.description
          value_field: "{{ slug }}"
          display_fields: ["topic.title"]
      - label: Body
        name: body
        widget: markdown
  - name: page
    label: Pages
    folder: src/content/page
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Description
        name: description
        widget: string
        required: true
      - label: Is Draft
        name: isDraft
        widget: boolean
        required: false
      - label: Thumbnail Image
        name: thumbnail
        widget: image
        required: false
      - label: Body
        name: body
        widget: markdown
  - name: topic
    label: Topics
    folder: src/content/topic
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Description
        name: description
        widget: string
        required: true
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Is Draft
        name: isDraft
        widget: boolean
        required: false
      - label: Thumbnail Image
        name: thumbnail
        widget: image
        required: false
      - label: Icon Name
        name: iconName
        widget: string
        required: false
      - label: Body
        name: body
        widget: markdown
